name: Feedback  
description: Share your thoughts to improve B&D's gameplay
title: "[Feedback]: "
labels: ["feedback"]
projects: ["konspiracy-games/1"]
body:
  - type: markdown
    attributes:
      value: "Have a look if [similar feedback has already been submitted](https://github.com/konspiracy-games/blossom-and-decay/issues?q=is%3Aissue%20label%3Afeature%2Cfeedback), please avoid duplicates.
      
      Before starting a report, please make sure to follow our [Reporting Guidelines](https://konspiracy.de/community_guidelines.html#Bug_Reports)."
  - type: input
    id: categories
    attributes:
      label: Categories
      description: Delete the categories that don't apply or add new ones at the end.
      placeholder: "If none of the categories was applicable, please write at least an applicable category for this bug."
      value: "world/map, balancing, offline play, UI, interaction, login, community, chat, tutorial, crafting/tasks, combat, character, gear, monsters/animals, map objects, items, territory, buildings, profile, settings..."
    validations:
      required: true
  - type: textarea
    id: problemrelated
    attributes:
      label: Is your feedback related to a problem?
      description: (if applicable) Recount you experience and observations.
      placeholder: "e.g. what feels wrong and/or doesn't work properly? when did you first noticed this? how can we observe it?"
  - type: textarea
    id: ideaMain
    attributes:
      label: Main Idea
      description: Describe you core idea as concise as possible (max. 2 paragraphs).
      placeholder: "e.g. e.g. what is it about? what need are you addressing? what would be its pros and cons? "
    validations:
      required: true
  - type: textarea
    id: ideaContext
    attributes:
      label: Idea reasoning/context
      description: Clear and concise arguments that expand on the relevance and applicability of your idea.
      placeholder: "e.g. why is this idea relevant? how does your idea improve gameplay? how would this unfold in our multiplayer world? how would this affect the offline AIs?"
    validations:
      required: true
  - type: textarea
    id: ideaAlter
    attributes:
      label: Solution alternatives
      description: Describe any alternative solutions you've considered around this topic.
      placeholder: |
        (if applicable) what solution could work in a similar way? what would be the down-/up-sides? why is your proposed idea preferable?
        if multiple solutions, please enumerate e.g.
        1.
        2.
        3.
        …
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description:  More info/context about your idea, suggestions, or screenshots (if available).
      placeholder: "What else should we know about this topic?"
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: "By submitting this bug report, you agree to allow the processing of your data by GitHub and our technical team for analysis and troubleshooting purposes in accordance with our [Privacy Policy](https://konspiracy.de/privacy_policy.html).\nAlso you confirm you are abiding by our [terms](https://konspiracy.de/terms_of_service.html) and the information provided is accurate and factual."
      options:
        - label: Yes, I do
          required: true
